enum PublicKeys {
    ASSET_COMMENT = 'ACTION_TYPE_ASSET_COMMENT',
    ASSET_UPLOAD = 'ACTION_TYPE_CLOTHING_ASSET_UPLOAD',
    FOLLOW_USER = 'ACTION_TYPE_FOLLOW_USER',
    GROUP_JOIN = 'ACTION_TYPE_GROUP_JOIN',
    WALL_POST = 'ACTION_TYPE_GROUP_WALL_POST',
    SUPPORT_REQUEST = 'ACTION_TYPE_SUPPORT_REQUEST',
    WEB_GAMECARD_REDEMPTION = 'ACTION_TYPE_WEB_GAMECARD_REDEMPTION',
    WEB_LOGIN = 'ACTION_TYPE_WEB_LOGIN',
    WEB_RESET_PASSWORD = 'ACTION_TYPE_WEB_RESET_PASSWORD',
    WEB_SIGNUP = 'ACTION_TYPE_WEB_SIGNUP',
}

export default PublicKeys;